### ISSUE TITLE
Object Storage 인프라 구축 및 파일 처리 API 개발

### ISSUE THREAD

**Issue by Zerohertz** [team-withiy/withiy-server#72]
## 개요
현재 서비스에서 이미지 및 파일 저장을 위한 Object Storage 인프라 구축이 필요합니다. 사용자 프로필 이미지, 장소/코스 이미지, 리뷰 이미지 등을 효율적으로 저장하고 관리할 수 있는 시스템이 필요합니다.

## 필요한 기능
- S3 호환 Object Storage 연동 (AWS S3 또는 MinIO)
- 파일 업로드/다운로드 API 개발
- 이미지 리사이징 및 최적화 기능
- 비공개/공개 접근 설정 기능
- 임시 URL 생성 기능 (Presigned URL)
- 파일 삭제 및 관리 기능

## 구현 사항
1. **Storage 설정 및 인프라**
   - AWS S3 또는 MinIO와 호환되는 설정
   - 개발/테스트/운영 환경별 설정 분리
   - 버킷 자동 생성 및 권한 설정

2. **이미지 처리 모듈**
   - 이미지 업로드 시 최적화 및 리사이징
   - 이미지 메타데이터 관리
   - 이미지 포맷 변환 기능 (필요시)

3. **API 엔드포인트**
   - `POST /api/files/upload`: 파일 업로드
   - `GET /api/files/{fileId}`: 파일 조회/다운로드
   - `DELETE /api/files/{fileId}`: 파일 삭제
   - `POST /api/files/presigned-url`: 임시 URL 발급 (클라이언트에서 직접 업로드용)

4. **서비스 통합**
   - User 서비스: 프로필 이미지 저장 및 관리
   - Place/Course 서비스: 장소 및 코스 이미지 관리
   - Review 서비스: 리뷰 이미지 업로드 및 관리

## 기술 스택
- Spring Boot
- AWS SDK for Java 또는 MinIO Client
- Spring Cloud AWS (S3 사용시)
- MinIO Java SDK (MinIO 사용시)
- ImgScalr 또는 Thumbnailator 라이브러리 (이미지 처리용)

## 구현 예시 코드
파일 업로드 서비스 구현 예시:
```java
@Service
@RequiredArgsConstructor
public class FileService {
    private final AmazonS3 s3Client;
    
    @Value("${aws.s3.bucket}")
    private String bucketName;
    
    public String uploadFile(MultipartFile file, String directory) {
        try {
            String fileName = generateFileName(file.getOriginalFilename());
            String fullPath = directory + "/" + fileName;
            
            ObjectMetadata metadata = new ObjectMetadata();
            metadata.setContentType(file.getContentType());
            metadata.setContentLength(file.getSize());
            
            s3Client.putObject(bucketName, fullPath, file.getInputStream(), metadata);
            
            return s3Client.getUrl(bucketName, fullPath).toString();
        } catch (IOException e) {
            throw new RuntimeException("파일 업로드 실패", e);
        }
    }
    
    public URL generatePresignedUrl(String key, HttpMethod method, int expirationMinutes) {
        java.util.Date expiration = new java.util.Date();
        expiration.setTime(expiration.getTime() + expirationMinutes * 60 * 1000);
        
        GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(bucketName, key)
                .withMethod(method)
                .withExpiration(expiration);
                
        return s3Client.generatePresignedUrl(request);
    }
    
    // 파일 다운로드, 삭제 등 추가 메서드
}
```

## 구성 예시
application-storage.yaml 예시:
```yaml
aws:
  s3:
    enabled: true
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION:ap-northeast-2}
    bucket: ${AWS_BUCKET_NAME:withiy-files}

# MinIO 사용 시
minio:
  enabled: false
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET_NAME:withiy-files}
```

## 테스트 고려사항
- MockS3 또는 Testcontainers를 사용한 MinIO 통합 테스트
- 다양한 파일 타입 및 크기에 대한 테스트
- 에러 처리 및 예외 상황 테스트

## 추가 고려사항
- 파일 크기 제한 설정
- 허용된 파일 타입 검증
- 보안 이슈 (CORS 설정, 접근 제어)
- CDN 연동 가능성 검토
- 높은 부하 상황에서의 성능 최적화

## 참고 자료
- [Spring Cloud AWS Documentation](https://docs.spring.io/spring-cloud-aws/docs/current/reference/html/)
- [MinIO Java Client Documentation](https://docs.min.io/docs/java-client-quickstart-guide.html)
- [AWS S3 Developer Guide](https://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html)
